# 数据配置
data:
  data_path: "data/data.csv"
  bert_model_path: "../bert/final_model"
  max_length: 512
  num_workers: 4

# 模型配置
model:
  bert_output_dim: 768
  num_labeled_classes: 107
  num_unlabeled_classes: 50
  freeze_bert: false

# 训练配置
train:
  epochs: 100
  batch_size: 32
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4
  warmup_teacher_temp: 0.07
  teacher_temp: 0.04
  warmup_teacher_temp_epochs: 30
  memax_weight: 2.0
  sup_con_weight: 0.35
  n_views: 2
  grad_from_block: 11
  print_freq: 10
  save_freq: 10

# 输出配置
output:
  exp_root: "outputs"
  exp_name: "simgcd_text_experiment"